"""Support invoice payments

Revision ID: f4005d62a61c
Revises: 4492fb1ec2b2
Create Date: 2019-02-18 10:53:09.530599+11:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4005d62a61c'
down_revision = '4492fb1ec2b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], [u'invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'invoices', sa.Column('status', sa.Integer(), server_default=sa.text(u'1'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'invoices', 'status')
    op.drop_table('invoice_payments')
    # ### end Alembic commands ###
